### ISSUE TITLE
Make new branch for Elgg > 2.1

### ISSUE THREAD

**Issue by gerard-kanters** [hypeJunction/Elgg-forms_register#2]
There are dependencies mentioned in manifest and composer which makes this plugin in its current form only usable for elgg 2.0 and 2.1

Please create a new branch for 2.2 and higher (with version in packagist). Remove the dependency for forms_api in composer and manifest and change manifest for release "lt" 2.1

Thanks.

**Comment by hypeJunction** [comment]
You can make a PR to change whatever is needed and I will make a new release. I am not going to maintain a branch for older Elgg versions, if someone needs it they can branch from release SHA.

**Comment by gerard-kanters** [comment]
I understand, the issue is that this branch is for older releases. I like a new branch for current  and future releases.

**Comment by hypeJunction** [comment]
Just make a PR against master
